[[redirects]]
	from = "/"
	to = "https://github.com/alecdotninja/travis-matrix-badge"
	status = 302

[[redirects]]
	from = "/badge-v1.svg"
	to = "/.netlify/functions/badge-v1"
	query = { owner = ":owner", repo = ":repo", branch = ":branch" }
	status = 200

[[redirects]]
	from = "/badge-v1.svg"
	to = "/.netlify/functions/badge-v1"
	query = { owner = ":owner", repo = ":repo" }
	status = 200

[build]
	command = "npm run build"
	functions = ".netlify/functions"